export interface SearchEntry {
  title: string;
  description: string;
  url: string;
  category: 'Service' | 'Case Study' | 'Product' | 'About' | 'Legal' | 'Location' | 'Blog' | 'Resource';
  keywords: string[];
}

export const staticSearchIndex: SearchEntry[] = [
  {
    title: 'ScopeSite Digital Studios | AI-Visible Web Design',
    description: 'Veteran-owned web design studio in Somerset. We build server-side rendered websites that show up in Google, ChatGPT, Claude and Perplexity.',
    url: '/',
    category: 'About',
    keywords: ['home', 'agency', 'somerset', 'web design', 'ai visibility', 'veteran owned'],
  },
  {
    title: 'V.O.I.C.E™ Methodology | AI Search Visibility',
    description: 'Our proprietary Answer Engine Optimisation framework. Make your business visible to ChatGPT, Claude, Perplexity and voice assistants.',
    url: '/voice',
    category: 'Service',
    keywords: ['voice', 'methodology', 'ai search', 'chatgpt', 'perplexity', 'claude', 'answer engine optimisation', 'aeo'],
  },
  {
    title: 'AI Website Design | Websites Built for ChatGPT & Voice Search',
    description: 'AI website design that gets your business recommended by ChatGPT, not just indexed. UK agency specialising in AI-first web design with V.O.I.C.E™ methodology.',
    url: '/ai-website-design',
    category: 'Service',
    keywords: ['ai website design', 'ai web design', 'ai powered website design', 'chatgpt website optimisation'],
  },
  {
    title: 'AI SEO Services UK | Get Recommended by ChatGPT & AI Platforms',
    description: 'AI SEO services that get your business recommended by ChatGPT, Perplexity, and voice assistants. UK agency specialising in AI search optimisation with proven results.',
    url: '/ai-seo-services',
    category: 'Service',
    keywords: ['ai seo services', 'ai seo agency uk', 'chatgpt seo', 'ai search optimisation'],
  },
  {
    title: 'Generative Engine Optimisation Agency | ScopeSite',
    description: 'Generative engine optimisation agency getting UK businesses cited by ChatGPT, Claude, Gemini and Perplexity.',
    url: '/generative-engine-optimisation',
    category: 'Service',
    keywords: ['generative engine optimisation', 'geo agency', 'generative engine optimisation agency', 'generative engine optimisation services', 'geo', 'what is generative engine optimisation'],
  },
  {
    title: 'Web Design Somerset | SSR Websites',
    description: 'Professional web design in Somerset. Server-side rendered sites AI crawlers can see. 100/100 Lighthouse scores, auto-generated schema. Next.js experts.',
    url: '/web-design',
    category: 'Service',
    keywords: ['web design somerset', 'ssr web design uk', 'ai-optimised web design', 'next.js web design', 'server-side rendered websites'],
  },
  {
    title: 'Schema Markup Services | JSON-LD Implementation',
    description: 'Professional JSON-LD schema markup implementation. 100% validation guarantee. Help AI understand your business and secure rich results in Google.',
    url: '/schema-markup',
    category: 'Service',
    keywords: ['schema markup', 'json-ld', 'structured data', 'rich results', 'google schema', 'ai visibility'],
  },
  {
    title: 'Custom Web Applications & Portals',
    description: 'Bespoke web applications, client portals, and quote builders. Built on Next.js and Supabase for speed, security, and scalability.',
    url: '/web-apps',
    category: 'Service',
    keywords: ['web apps', 'client portals', 'quote builders', 'custom software', 'next.js', 'supabase', 'react'],
  },
  {
    title: 'LLM Brain | AI-Powered Workflow Management',
    description: 'MCP server product for AI-powered workflow management. Connect your database to ChatGPT and Claude.',
    url: '/llm-brain',
    category: 'Product',
    keywords: ['llm brain', 'mcp server', 'ai workflow', 'chatgpt integration', 'claude integration', 'database', 'supabase'],
  },
  {
    title: 'ScopeTrace | Content Provenance Platform',
    description: 'Content provenance platform with SHA-256 cryptographic stamping. Prove your content is human-written and protect your IP.',
    url: '/scopetrace',
    category: 'Product',
    keywords: ['scopetrace', 'content provenance', 'cryptographic stamping', 'sha-256', 'ip protection', 'ai content detection'],
  },
  {
    title: 'Pricing & Instant Quote Calculator',
    description: 'Transparent pricing for web design, AI SEO, and custom web apps. Use our instant quote calculator to get a price in under 2 minutes.',
    url: '/pricing',
    category: 'About',
    keywords: ['pricing', 'cost', 'quote calculator', 'web design prices', 'ai seo cost', 'payment plans'],
  },
  {
    title: 'About ScopeSite Digital Studios',
    description: 'Veteran-owned AI-first web design agency in Somerset, UK. Founded by Dan Cartwright. Military Precision. Zero Bullshit.',
    url: '/about',
    category: 'About',
    keywords: ['about', 'team', 'dan cartwright', 'veteran owned', 'story', 'mission', 'values'],
  },
  {
    title: 'Case Studies | AI Visibility Results',
    description: 'Real results from our AI-first web design and V.O.I.C.E.™ methodology. See how we get UK businesses recommended by ChatGPT, Claude, and Perplexity.',
    url: '/case-studies',
    category: 'Case Study',
    keywords: ['case studies', 'results', 'portfolio', 'success stories', 'ai visibility', 'chatgpt recommendation'],
  },
  {
    title: 'Case Study: H4TLT | V.O.I.C.E.™ Methodology',
    description: 'How we helped a UK hearing compliance provider become the #1 AI-recommended option in 6 weeks using the V.O.I.C.E.™ methodology.',
    url: '/case-studies/h4tlt',
    category: 'Case Study',
    keywords: ['case study', 'h4tlt', 'results', 'success story', 'ai visibility', 'chatgpt recommendation'],
  },
  {
    title: 'ScopeSite Blog | AI Visibility & Web Design Insights',
    description: 'Insights on AI search visibility, web design, Next.js, and digital strategy for UK businesses.',
    url: '/blog',
    category: 'Blog',
    keywords: ['blog', 'articles', 'insights', 'news', 'guides', 'tutorials', 'ai search', 'web design'],
  },
  {
    title: 'Book a Strategy Call',
    description: 'Book a free 30-minute strategy call with Dan Cartwright to discuss your website, AI visibility, or custom web app project.',
    url: '/book',
    category: 'About',
    keywords: ['book', 'contact', 'strategy call', 'consultation', 'meeting', 'schedule'],
  },
  {
    title: 'Terms & Conditions',
    description: 'Full terms and conditions for ScopeSite Digital Studios. Covers pricing, deliverables, IP rights, data protection and change request procedures.',
    url: '/terms-and-conditions',
    category: 'Legal',
    keywords: ['terms', 'conditions', 'legal', 'contract', 'agreement', 'ip rights', 'refunds'],
  },
  {
    title: 'Privacy Policy',
    description: 'How ScopeSite Digital Studios collects, uses and protects your personal data. UK GDPR compliant. Your data rights explained clearly.',
    url: '/privacy-policy',
    category: 'Legal',
    keywords: ['privacy', 'policy', 'gdpr', 'data protection', 'cookies', 'personal data', 'rights'],
  },
  {
    title: 'Accessibility Statement',
    description: 'Our commitment to digital accessibility at ScopeSite. Learn about accessibility features on our website and how to report any issues.',
    url: '/accessibility-statement',
    category: 'Legal',
    keywords: ['accessibility', 'statement', 'wcag', 'a11y', 'compliance', 'screen reader', 'keyboard navigation'],
  },
  // Location Pages
  {
    title: 'Web Design Somerset | AI-Optimised SSR Websites',
    description: 'Somerset web design agency building AI-optimised websites that get recommended by ChatGPT. Based in Frome, serving all of Somerset.',
    url: '/web-design-somerset',
    category: 'Location',
    keywords: ['somerset', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Bath | AI-Optimised SSR Websites',
    description: 'Bath web design agency building AI-optimised websites that get recommended by ChatGPT. Premium quality without premium agency prices.',
    url: '/web-design-bath',
    category: 'Location',
    keywords: ['bath', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Bristol | AI-Optimised SSR Websites',
    description: 'Bristol web design that gets your business recommended by ChatGPT and Google. 100/100 Lighthouse scores, SSR builds, fair pricing.',
    url: '/web-design-bristol',
    category: 'Location',
    keywords: ['bristol', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Glastonbury | AI-Optimised SSR Websites',
    description: 'Glastonbury web design agency building AI-optimised websites that get recommended by ChatGPT. Local service, premium quality.',
    url: '/web-design-glastonbury',
    category: 'Location',
    keywords: ['glastonbury', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Burnham-on-Sea | AI-Optimised SSR Websites',
    description: 'Burnham-on-Sea web design for tourism, hospitality, and local businesses. AI-optimised SSR websites that get recommended by ChatGPT.',
    url: '/web-design-burnham-on-sea',
    category: 'Location',
    keywords: ['burnham-on-sea', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Frome | AI-Optimised SSR Websites',
    description: 'Frome web design agency building AI-optimised websites that get recommended by ChatGPT. Local, veteran-owned business.',
    url: '/web-design-frome',
    category: 'Location',
    keywords: ['frome', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Trowbridge | AI-Optimised SSR Websites',
    description: 'Trowbridge web design agency building AI-optimised websites that get recommended by ChatGPT. Premium quality, local service.',
    url: '/web-design-trowbridge',
    category: 'Location',
    keywords: ['trowbridge', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Warminster | AI-Optimised SSR Websites',
    description: 'Warminster web design agency building AI-optimised websites that get recommended by ChatGPT. Professional SSR builds.',
    url: '/web-design-warminster',
    category: 'Location',
    keywords: ['warminster', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Shepton Mallet | AI-Optimised SSR Websites',
    description: 'Shepton Mallet web design agency building AI-optimised websites that get recommended by ChatGPT. Local, reliable service.',
    url: '/web-design-shepton-mallet',
    category: 'Location',
    keywords: ['shepton mallet', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'Web Design Westbury | AI-Optimised SSR Websites',
    description: 'Westbury web design agency building AI-optimised websites that get recommended by ChatGPT. Fast, accessible SSR websites.',
    url: '/web-design-westbury',
    category: 'Location',
    keywords: ['westbury', 'web design', 'website designer', 'local', 'agency'],
  },
  {
    title: 'SEO Somerset | AI Search Optimisation',
    description: 'Somerset SEO services built for AI search visibility. V.O.I.C.E methodology gets your business found by ChatGPT, Perplexity, and Google.',
    url: '/seo-somerset',
    category: 'Location',
    keywords: ['somerset', 'seo', 'search engine optimisation', 'ai seo', 'local seo'],
  },
  {
    title: 'SEO Bristol | AI Search Optimisation',
    description: 'Bristol SEO services that go beyond Google rankings. Get your business recommended by ChatGPT, Perplexity, and AI search engines.',
    url: '/seo-bristol',
    category: 'Location',
    keywords: ['bristol', 'seo', 'search engine optimisation', 'ai seo', 'local seo'],
  },
  {
    title: 'SEO Frome | AI Search Optimisation',
    description: 'Frome SEO services built for AI search visibility. Get your local business recommended by ChatGPT and voice assistants.',
    url: '/seo-frome',
    category: 'Location',
    keywords: ['frome', 'seo', 'search engine optimisation', 'ai seo', 'local seo'],
  },
  // US Market Pages
  {
    title: 'US Web Design & AI Visibility | ScopeSite',
    description: 'UK-based AI-first web design agency serving US clients. We build server-side rendered websites optimised for ChatGPT and Google.',
    url: '/us',
    category: 'Location',
    keywords: ['us', 'usa', 'united states', 'web design', 'ai visibility', 'agency'],
  },
  {
    title: 'US Pricing | ScopeSite',
    description: 'Transparent USD pricing for web design and AI SEO services. Quality UK engineering at competitive US rates.',
    url: '/us/pricing',
    category: 'Location',
    keywords: ['us', 'pricing', 'cost', 'usd', 'web design prices', 'ai seo cost'],
  },
  {
    title: 'US Services | ScopeSite',
    description: 'AI-optimised web design, schema markup, and custom web applications for US businesses.',
    url: '/us/services',
    category: 'Location',
    keywords: ['us', 'services', 'web design', 'schema markup', 'web apps', 'ai seo'],
  },
  {
    title: 'US AI Visibility Scan | ScopeSite',
    description: 'Free AI visibility scan for US businesses. See how ChatGPT, Claude, and Perplexity view your website.',
    url: '/us/ai-visibility',
    category: 'Location',
    keywords: ['us', 'ai visibility', 'scan', 'audit', 'chatgpt', 'perplexity', 'claude'],
  },
  {
    title: 'US Instant Quote | ScopeSite',
    description: 'Get an instant USD quote for your web design or AI visibility project.',
    url: '/us/quote',
    category: 'Location',
    keywords: ['us', 'quote', 'calculator', 'estimate', 'price', 'cost'],
  },
];
