/**
 * Fallback SVG mockup for a "Google AI Overview" ProofSection card.
 *
 * Renders when the corresponding .webp / .png hasn't been dropped into
 * public/territory/proof/ yet. Purely decorative - the real screenshots
 * always win when they exist (see resolveProofImage).
 *
 * Variants:
 *  - somerset-seo      -> query "ai seo somerset" answered with ScopeSite / AI visibility
 *  - voice-category    -> query "what is AI visibility score" answered categorically
 */

interface Props {
  variant: 'somerset-seo' | 'voice-category';
  className?: string;
}

const COPY: Record<Props['variant'], { query: string; lines: string[]; chips: string[] }> = {
  'somerset-seo': {
    query: 'ai seo somerset',
    lines: [
      'ScopeSite Digital Studios applies an AI visibility',
      'methodology to Somerset firms to engineer visibility',
      'across AI answer engines.',
      'The framework covers structured data, speed, crawler',
      'access, authority, and content clarity.',
    ],
    chips: ['scopesite.co.uk', 'scopesite.co.uk/voice'],
  },
  'voice-category': {
    query: 'what is ai visibility score',
    lines: [
      'AI visibility score is how we summarise citation',
      'readiness: how well models can read, trust, and',
      'recommend your brand across ChatGPT, Perplexity, Claude',
      'and Google AI Overviews. Scores run from 0 to 100.',
    ],
    chips: ['scopesite.co.uk/voice', 'scopesite.co.uk'],
  },
};

export function AIOverviewMockup({ variant, className }: Props) {
  const { query, lines, chips } = COPY[variant];

  return (
    <svg
      viewBox="0 0 400 300"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label={`Illustrative mockup of a Google AI Overview for the query "${query}"`}
      preserveAspectRatio="xMidYMid slice"
      className={className}
    >
      <defs>
        <linearGradient id="aio-bg" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#FFFFFF" />
          <stop offset="100%" stopColor="#F0F7FF" />
        </linearGradient>
        <linearGradient id="aio-border" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="#4285F4" />
          <stop offset="50%" stopColor="#A855F7" />
          <stop offset="100%" stopColor="#EA4335" />
        </linearGradient>
      </defs>

      <rect width="400" height="300" fill="#F8FAFC" />

      {/* Browser chrome suggestion */}
      <rect x="16" y="16" width="368" height="24" rx="6" fill="#E5E7EB" />
      <circle cx="28" cy="28" r="3" fill="#EF4444" />
      <circle cx="40" cy="28" r="3" fill="#F59E0B" />
      <circle cx="52" cy="28" r="3" fill="#22C55E" />
      <rect x="68" y="22" width="300" height="12" rx="3" fill="#F3F4F6" />
      <text
        x="76"
        y="31"
        fontFamily="system-ui, sans-serif"
        fontSize="9"
        fill="#64748B"
      >
        google.com/search?q={query.replaceAll(' ', '+')}
      </text>

      {/* Search query */}
      <rect x="16" y="48" width="368" height="28" rx="14" fill="#FFFFFF" stroke="#E5E7EB" />
      <text
        x="32"
        y="66"
        fontFamily="system-ui, sans-serif"
        fontSize="11"
        fill="#0A1B36"
        fontWeight="500"
      >
        {query}
      </text>
      <circle cx="368" cy="62" r="6" fill="none" stroke="#94A3B8" strokeWidth="1.5" />
      <line x1="372" y1="66" x2="376" y2="70" stroke="#94A3B8" strokeWidth="1.5" strokeLinecap="round" />

      {/* AI Overview card */}
      <rect
        x="18"
        y="88"
        width="364"
        height="198"
        rx="14"
        fill="url(#aio-bg)"
        stroke="url(#aio-border)"
        strokeWidth="1.5"
      />

      {/* AI Overview header row */}
      <g transform="translate(32 104)">
        <path
          d="M8,0 L10,6 L16,8 L10,10 L8,16 L6,10 L0,8 L6,6 Z"
          fill="#4285F4"
        />
        <text
          x="22"
          y="12"
          fontFamily="system-ui, sans-serif"
          fontSize="11"
          fontWeight="700"
          fill="#0A1B36"
        >
          AI Overview
        </text>
        <text
          x="92"
          y="12"
          fontFamily="system-ui, sans-serif"
          fontSize="9"
          fill="#64748B"
        >
          Generated by AI
        </text>
      </g>

      {/* Mock answer paragraphs */}
      <g
        fontFamily="system-ui, sans-serif"
        fontSize="10"
        fill="#1F2937"
      >
        {lines.map((line, i) => (
          <text key={i} x="32" y={138 + i * 14}>
            {line}
          </text>
        ))}
      </g>

      {/* Sources row */}
      <g transform={`translate(32 ${138 + lines.length * 14 + 8})`}>
        <text
          fontFamily="system-ui, sans-serif"
          fontSize="9"
          fontWeight="700"
          fill="#64748B"
          x="0"
          y="0"
        >
          Sources
        </text>
        {chips.map((chip, i) => {
          const x = i * 148;
          return (
            <g key={chip} transform={`translate(${x} 8)`}>
              <rect width="140" height="22" rx="11" fill="#FFFFFF" stroke="#CBD5E1" />
              <circle cx="14" cy="11" r="5" fill="#F5B700" />
              <text
                x="26"
                y="15"
                fontFamily="system-ui, sans-serif"
                fontSize="9"
                fontWeight="600"
                fill="#0A1B36"
              >
                {chip}
              </text>
            </g>
          );
        })}
      </g>
    </svg>
  );
}

export default AIOverviewMockup;
